# Generated by Django 3.0.8 on 2020-11-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='fingerprint',
            field=models.CharField(default='llllll', max_length=100),
            preserve_default=False,
        ),
    ]
