# Generated by Django 3.0.8 on 2020-11-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20201113_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
