# Generated by Django 3.0.8 on 2020-11-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_card_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='payment_method',
            field=models.CharField(max_length=100),
        ),
    ]
