# Generated by Django 3.0.8 on 2020-08-28 09:19

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20200828_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(related_name='cart', to='store.Product'),
        ),
        migrations.AlterField(
            model_name='shippingadress',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
