# Generated by Django 3.0.8 on 2020-09-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20200904_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_addres',
            new_name='shipping_address',
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(related_name='cart', to='store.Product'),
        ),
    ]
