# Generated by Django 3.0.8 on 2020-09-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20200911_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(related_name='cart', to='store.Product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
