# Generated by Django 3.0.8 on 2020-09-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_emailtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoken',
            name='token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
